spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        naming:
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        temp:
          use_jdbc_metadata_defaults: false
    hibernate:
      ddl-auto: none
  flyway:
    locations: classpath:db/migration
    enabled: true
